//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CashierSet> CashierSet { get; set; }
        public DbSet<DoctorSet> DoctorSet { get; set; }
        public DbSet<PatientSet> PatientSet { get; set; }
        public DbSet<ProcessSet> ProcessSet { get; set; }
        public DbSet<RoomSet> RoomSet { get; set; }
    }
}
